### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by julianshutt** [julianshutt/sergeant-wilson#1]
Bits that would be worth doing,

- [x] get tests from a file source
- [x] generally improve error handling and re-instigating dropped connections
- [x] configure the thing to get lost!
- [x] total the PASS, FAIL and skip results for immediate consumption
